set(SOURCES
    SOURCE/Components/CreatePresetView.h
    SOURCE/Components/EnvelopeControlPoint.h
    SOURCE/Components/EnvelopeVisualizer.cpp
    SOURCE/Components/EnvelopeVisualizer.h
    SOURCE/Components/PluginEditor.cpp
    SOURCE/Components/PluginEditor.h
    SOURCE/Components/PluginMainView.cpp
    SOURCE/Components/PluginMainView.h
    SOURCE/Components/PresetManagerView.h
    SOURCE/Components/PulsarControlsComponent.cpp
    SOURCE/Components/PulsarControlsComponent.h
    SOURCE/Components/PulsarSlider.cpp
    SOURCE/Components/PulsarSlider.h
    SOURCE/Components/PulsaretVisualizer.cpp
    SOURCE/Components/PulsaretVisualizer.h
    SOURCE/Database.h
    SOURCE/Envelope/Envelope.cpp
    SOURCE/Envelope/Envelope.h
    SOURCE/LookNFeel/MixFeel.cpp
    SOURCE/LookNFeel/MixFeel.h
    SOURCE/LookNFeel/NameFeel.cpp
    SOURCE/LookNFeel/NameFeel.h
    SOURCE/LookNFeel/PulsarUIFeel.cpp
    SOURCE/LookNFeel/PulsarUIFeel.h
    SOURCE/PULSAR_TRAIN/PulsarTrain.cpp
    SOURCE/PULSAR_TRAIN/PulsarTrain.h
    SOURCE/Processor/PluginProcessor.cpp
    SOURCE/Processor/PluginProcessor.h
    SOURCE/Processor/TempoSync.cpp
    SOURCE/Processor/TempoSync.h
    SOURCE/PulsarSynthesiser.cpp
    SOURCE/PulsarSynthesiser.h
    SOURCE/Pulsaret/MidiTransformer.cpp
    SOURCE/Pulsaret/MidiTransformer.h
    SOURCE/Pulsaret/OwnedPulsaret.cpp
    SOURCE/Pulsaret/OwnedPulsaret.h
    SOURCE/Pulsaret/Pulsaret.cpp
    SOURCE/Pulsaret/Pulsaret.h
    SOURCE/Pulsaret/PulsaretFactory.cpp
    SOURCE/Pulsaret/PulsaretFactory.h
    SOURCE/Pulsaret/PulsaretTable.cpp
    SOURCE/Pulsaret/PulsaretTable.h
    SOURCE/Pulsaret/Table.cpp
    SOURCE/Pulsaret/Table.h
    SOURCE/Util/PresetPaths.h
    SOURCE/Util/Version.h
)